site: elk.engineer
url: #yoururl
title: elk.engineer
description: wilderness of code.
twitter:
  username: djjonno91
  card: summary
  creator: djjonno91
medium:
  username: jonathonscanes
author:
  twitter: djjonno91
  name: Jonathon
  avatar:
  email: jonathon.scanes@gmail.com
  url: djjonno91
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"